services:
    - type: web
    name: manasse-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
            - key: GEMINI_KEY
        sync: false
